### PR TITLE
chore: remove unused envs from readme.md

### PR DESCRIPTION
**Pull request by Anmol1696**
## Overview
From the struct of the [`TargetChainConfig`](https://github.com/neutron-org/neutron-query-relayer/blob/main/internal/config/config.go#L46), both AccountPrefix and ValidatorAccountPrefix dont seme to be used anymore. 
Since it is still present in the readme, it is a little confusing for the setup.

### CODE REVIEW

**Review by NeverHappened — APPROVED** [review]
lgtm, thanks!

**Review by foxpy — APPROVED** [review]
Seems like we removed these options but forgot to update the README.

**Comment by Anmol1696** [comment]
Is there anything else I can do to get the CI working and get the PR merged?

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-query-relayer/pull/88#issuecomment-2041055188
No, we'll merge it soon, big thanks for the help!

**Review by pr0n00gler — APPROVED** [review]

**Pull request merged**
